FROM openjdk:11
VOLUME /tmp
ADD ./target/hr-worker-1.0.0.jar hr-worker.jar
ENTRYPOINT ["java","-jar","/hr-worker.jar"]

# To build the image execute: 
# docker build -t hr-worker:v1 .
# To run a container execute: 
# docker run -P --network hr-net hr-worker:v1