FROM openjdk:11
VOLUME /tmp
ADD ./target/hr-api-gateway-zuul-1.0.0.jar hr-api-gateway-zuul.jar
ENTRYPOINT ["java","-jar","/hr-api-gateway-zuul.jar"]

# To build the image execute: 
# docker build -t hr-api-gateway-zuul:v1 .
# To run a container execute: 
# docker run -p 8765:8765 --name hr-api-gateway-zuul --network hr-net hr-api-gateway-zuul:v1