FROM openjdk:11
VOLUME /tmp
ADD ./target/hr-oauth-1.0.0.jar hr-oauth.jar
ENTRYPOINT ["java","-jar","/hr-oauth.jar"]

# To build the image execute: 
# docker build -t hr-oauth:v1 .
# To run a container execute: 
# docker run -P --network hr-net hr-oauth:v1