FROM openjdk:11
VOLUME /tmp
EXPOSE 8761
ADD ./target/hr-eureka-server-1.0.0.jar hr-eureka-server.jar
ENTRYPOINT ["java","-jar","/hr-eureka-server.jar"]

# To create the image:
# docker build -t hr-eureka-server:v1 .
#
# To run the container:
# docker run -p 8761:8761 --name hr-eureka-server --network hr-net hr-eureka-server:v1